#!/usr/bin/env bash
# Generated by stoatworks-unraid/scripts/gen-launcher.mjs from fleet.json.
# Repo: willmyshowfit. Edit fleet.json and regenerate — direct edits are overwritten.
#
# Stage the site the desktop app serves: build it from the repo (or take the
# committed copy), then copy it to src-tauri/site/, which tauri.conf.json
# bundles as a resource and launcher.toml serves as {resource}/site.
#
# Run before `npm run tauri build` or `npm run tauri dev`.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"     # launcher/
REPO="$(cd "$HERE/.." && pwd)"               # the willmyshowfit repo root
SITE="$HERE/src-tauri/site"

echo "==> building the site (npm run build)"
( cd "$REPO" && npm ci --no-audit --no-fund && npm run build )
SRC="$REPO/dist"

[ -f "$SRC/index.html" ] || { echo "error: $SRC has no index.html — nothing to serve" >&2; exit 1; }

echo "==> staging $SRC -> src-tauri/site"
rm -rf "$SITE"
mkdir -p "$SITE"
cp -R "$SRC/." "$SITE/"
# Cloudflare's redirect file has no meaning here; _headers stays, the launcher
# reads it and never serves it.
rm -f "$SITE/_redirects"
echo "staged $(find "$SITE" -type f | wc -l | tr -d ' ') files"
